# 워크플로 이름
name: Basic Workflow

# 트리거 조건 설정
on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

# 작업 정의
jobs:
  build:
    # 실행 환경
    runs-on: ubuntu-latest

    # 작업 단계
    steps:
      # 1단계: 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2단계: 스크립트 실행
      - name: Run a script
        run: echo "Hello, GitHub Actions!"
